name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
      fail-fast: true
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.18.0

      - name: Verify formatting
        run: deno fmt --config deno.json

      - name: Run linter
        run: deno lint --config deno.json

      - name: Run Test
        run: deno test --coverage=cov_profile --allow-net --allow-read --allow-write --unstable tests

      - name: Create cov report
        if: matrix.os == 'ubuntu-latest'
        run: deno coverage cov_profile --lcov > cov_profile.lcov

      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          path-to-lcov: cov_profile.lcov